[workspace]
resolver = "3"
members = [
    "crates/atomex",
    "crates/abs_iter",

    "crates/abs_cancel",
    "crates/abs_sync",
    "crates/atomic_sync",
    "crates/gen_mcf_macro",
    "crates/gen_mcf_test",

    "crates/abs_buff",
    "crates/abs_buff_stdio_adapt",
    "crates/abs_buff_tokio_adapt",
    "crates/buffex",

    "crates/cancel_src",

    "crates/abs_vfs",
    "crates/mem_vfs",

    "crates/abs_smux",
    "crates/smux_v1",
]

[workspace.package]
edition = "2024"
authors = ["lino <lino_snsalias@outlook.com>"]

[workspace.dependencies]
funty = { version = "3.0.0-rc2", default-features = false }
pin-project = { version = "1.1.*" }
pin-utils = { version = "*" }
env_logger = { version = "0.11.*" }
log = { version = "0.4.*" }
futures-lite = { version = "2" }
compio = { version = "0.19.*", features = ["fs", "macros", "time"] }
thiserror = { version = "2.0", default-features = false }
